---
# MOMNIT CONFIGURATION

- name: unzip monit file on destiny
  unarchive: src="./files/{{monit_file}}" dest="{{destiny_path}}/"
  register: result
  ignore_errors: True

- name: download monit if doesnt exists
  local_action: wget "{{monit_download_url}}/{{monit_version}}/{{monit_file}}" -P "./roles/monit/files/"
  when: result|failed

- name: trying again to unzip monit file on destiny
  unarchive: src="./roles/monit/files/{{monit_file}}" dest="{{destiny_path}}/"
  when: result|failed

- name: changing dir name
  command: mv "{{destiny_path}}/{{monit_orig_dir_name}}" "{{destiny_path}}/monit"

- name: create monit rc dir
  command: mkdir "{{destiny_path}}/monit/rc/"

- name: create monit log dir
  command: mkdir "{{destiny_path}}/monit/rc/log/"

- name: create monit events dir
  command: mkdir "{{destiny_path}}/monit/rc/events"

- name: create monitrc file
  template:
    src="./roles/monit/templates/monitrc"
    dest="{{monitrc_file_destiny}}/"

- name: create link to monitrc file
  command: ln -sf "{{destiny_path}}/monit/monitrc" "~/.monitrc"

- name: changing monitrc permissions
  action: file path={{monitrc_file_destiny}}/monitrc mode=0700
  notify:
    - start monit
