---
# MOMNIT CONFIGURATION

- name: unzip monit file on destiny
  unarchive: src="./files/{{monit_file}}" dest="{{destiny_path}}/"

- name: changing dir name
  command: mv "{{destiny_path}}/{{monit_orig_dir_name}}" "{{destiny_path}}/monit"

- name: create monit rc dir
  command: mkdir "{{destiny_path}}/monit/rc/"

- name: create monit log dir
  command: mkdir "{{destiny_path}}/monit/rc/log/"

- name: create monit events dir
  command: mkdir "{{destiny_path}}/monit/rc/events"

- name: create monitrc file
  template:
    src="./templates/monitrc"
    dest="{{monitrc_file_destiny}}/"

- name: changing monitrc permissions
  action: file path={{monitrc_file_destiny}}/monitrc mode=0700
